// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dviuujohjxynywfamgdr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR2aXV1am9oanh5bnl3ZmFtZ2RyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyNjc0MzEsImV4cCI6MjA3Mzg0MzQzMX0.QxU6iYwxILRDOCtr7fu_Sia00wb1I0zjLMKPRBJcGr4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});